name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install depndencies
        run: |
          python -m venv myenv
          myenv\Scripts\activate
          pip install -r requirements.txt

      - name: Run tests
        run: python --version